{% set name = "lru-dict" %}
{% set version = "1.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 878bc8ef4073e5cfb953dfc1cf4585db41e8b814c0106abde34d00ee0d0b3115

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - lru
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/amitdev/lru-dict
  summary: An Dict like LRU container.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
